//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimiSoft.InformationCollection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int FeedbackId { get; set; }
        public int UserId { get; set; }
        public int SourceId { get; set; }
        public string Content { get; set; }
        public System.DateTime SubmitTime { get; set; }
        public string Response { get; set; }
        public Nullable<System.DateTime> ResponseTime { get; set; }
    }
}
