//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimiSoft.InformationCollection.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ICContext : DbContext
    {
        public ICContext()
            : base("name=ICContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SourceRegex> SourceRegexes { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<UserSourceContentLink> UserSourceContentLinks { get; set; }
        public DbSet<SourceRegexGroup> SourceRegexGroups { get; set; }
        public DbSet<Source> Sources { get; set; }
        public DbSet<UserSourceLink> UserSourceLinks { get; set; }
        public DbSet<SourceContent> SourceContents { get; set; }
        public DbSet<UserSourceContentFavorLink> UserSourceContentFavorLinks { get; set; }
        public DbSet<Feedback> Feedbacks { get; set; }
        public DbSet<SourceUrl> SourceUrls { get; set; }
    }
}
