//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimiSoft.InformationCollection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceContent
    {
        public int SourceId { get; set; }
        public string Content { get; set; }
        public int ContentType { get; set; }
        public string Url { get; set; }
        public System.DateTime AddTime { get; set; }
        public int SourceContentId { get; set; }
    
        public virtual Source Source { get; set; }
    }
}
