//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimiSoft.InformationCollection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Source
    {
        public Source()
        {
            this.UserSourceLinks = new HashSet<UserSourceLink>();
            this.SourceContents = new HashSet<SourceContent>();
        }
    
        public int SourceId { get; set; }
        public string SourceName { get; set; }
        public string Url { get; set; }
        public System.DateTime AddTime { get; set; }
        public string Domain { get; set; }
        public int Interval { get; set; }
    
        public virtual ICollection<UserSourceLink> UserSourceLinks { get; set; }
        public virtual ICollection<SourceContent> SourceContents { get; set; }
    }
}
