//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimiSoft.InformationCollection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSourceContentLink
    {
        public int UserSourceContentLinkId { get; set; }
        public int UserId { get; set; }
        public int SourceContentId { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual SourceContent SourceContent { get; set; }
    }
}
