//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimiSoft.InformationCollection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.UserSourceContentLinks = new HashSet<UserSourceContentLink>();
            this.UserSourceLinks = new HashSet<UserSourceLink>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<UserSourceContentLink> UserSourceContentLinks { get; set; }
        public virtual ICollection<UserSourceLink> UserSourceLinks { get; set; }
    }
}
