//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimiSoft.InformationCollection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSourceLink
    {
        public int UserSourceLinkId { get; set; }
        public int SourceId { get; set; }
        public int UserId { get; set; }
        public System.DateTime AddTime { get; set; }
    
        public virtual Source Source { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
